### ISSUE TITLE
Consider using pyproject.toml

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pyansys_landing#13]
As noted by @greschd, we can incorporate the use of `pyproject.toml` and "pin" certain pyansys packages that we know have been tested and are compatible to allow the user to install the the latest pyansys packages for a certain release. Potentially in the following manner (up for discussion):

```
pip install pyansys==2022R1
```

We could also install individual packages with:
```
pip install pyansys[mapdl]
```
or
```
pip install pyansys[pymapdl]
```

**Comment by RobPasMue** [comment]
This one will be solved on #34
