### ISSUE TITLE
Minor display issue in documentation

### ISSUE THREAD

**Issue by pmaroneh** [pyansys/pyansys_landing#5]
From https://docs.pyansys.com/# the right panel displays as follows:
![image](https://user-images.githubusercontent.com/76440649/131689093-44c03a68-d4a7-45dc-a729-a15cfe68c856.png)
But I believe the "Connect to Desktop from Python" section should be within the "PyAEDT" section.

**Comment by akaszynski** [comment]
This will be fixed when we push the next "release".
